name: Go

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  build:
    name: build ${{ matrix.target_os }}_${{ matrix.target_arch }} binaries
    runs-on: ubuntu-latest
    env:
      GOVER: 1.17
      GOOS: ${{ matrix.target_os }}
      GOARCH: ${{ matrix.target_arch }}

    strategy:
      matrix:
        target_os: [linux, darwin, windows]
        target_arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOVER }}
          go-os: ${{ matrix.target_os }}
          go-arch: ${{ matrix.target_arch }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: tar binary
        if: matrix.target_os != 'windows'
        run: |
          chmod +x sping
          tar cf sping_${{ matrix.target_os }}_${{ matrix.target_arch }}.tar.gz sping

      - uses: actions/upload-artifact@v2
        if: matrix.target_os != 'windows'
        with:
          name: sping_${{ matrix.target_os }}_${{ matrix.target_arch }}
          path: sping_${{ matrix.target_os }}_${{ matrix.target_arch }}.tar.gz

      - uses: actions/upload-artifact@v2
        if: matrix.target_os == 'windows'
        with:
          name: sping_${{ matrix.target_os }}_${{ matrix.target_arch }}
          path: sping.exe
